on:
  push:
    branches:
      - test-workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch the readme
        run: curl https://leoadec.github.io > README.md
      - name: Commit changes
        run: |
          git config --global user.email "leoadec@gmail.com"
          git config --global user.name "leoadec"
          git commit -am 'update README'
          git push
