on:
  push:
    branches:
      - test-workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout README repo
        uses: actions/checkout@v3
      - name: Checkout website
        uses: actions/checkout@v3
        with:
          repository: leoadec/leoadec.github.io
          path: website
      - name: Fetch the readme
        run: cp website/_includes/summary.html README.md
      - name: Commit changes
        run: |
          git config --global user.email "leoadec@gmail.com"
          git config --global user.name "leoadec"
          git commit -am 'update README'
          git push
